// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroProductosDetalles.DAL;

#nullable disable

namespace RegistroProductosDetalles.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("RegistroProductosDetalles.Entidades.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ganancia")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("RegistroProductosDetalles.Entidades.ProductosDetalles", b =>
                {
                    b.Property<int>("ProductosDetallesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<string>("Presentacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductosDetallesId");

                    b.HasIndex("ProductosId");

                    b.ToTable("ProductosDetalles");
                });

            modelBuilder.Entity("RegistroProductosDetalles.Entidades.ProductosDetalles", b =>
                {
                    b.HasOne("RegistroProductosDetalles.Entidades.Productos", null)
                        .WithMany("ProductosDetalles")
                        .HasForeignKey("ProductosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistroProductosDetalles.Entidades.Productos", b =>
                {
                    b.Navigation("ProductosDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
